# Generated by Django 4.2.3 on 2023-07-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_registerpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerpage',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
