# Generated by Django 4.2.3 on 2023-07-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_registerpage_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterPage',
            new_name='RegisterModel',
        ),
        migrations.RenameModel(
            old_name='SigninPage',
            new_name='SigninModel',
        ),
        migrations.RenameModel(
            old_name='SignupPage',
            new_name='SignupModel',
        ),
    ]
