# Generated by Django 4.2.3 on 2023-07-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_registerpage_registermodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermodel',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Province',
            new_name='province',
        ),
    ]
